{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "burpsuite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "burpsuite.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "burpsuite.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.web.ingress.enabled }}
  - from:
    - namespaceSelector: {{ toYaml .Values.networkPolicy.ingressControllerNamespaceSelector | nindent 8 }}
    - podSelector: {{ toYaml .Values.networkPolicy.ingressControllerPodSelector | nindent 8 }}
    ports:
    - protocol: TCP
      port: 8080
  {{- end }}
  {{- range .Values.networkPolicy.ingress }}
  - {{ toYaml . | nindent 4 | trim }}
  {{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  # BEGIN - portswigger.net static IPs
  - to:
    - ipBlock:
        cidr: 34.240.117.4/32
    - ipBlock:
        cidr: 34.249.63.188/32
    ports:
    - protocol: TCP
      port: 443
  # END - portswigger.net static IPs
  {{- range .Values.networkPolicy.egress }}
  - {{ toYaml . | nindent 4 | trim }}
  {{- end }}
{{- end }}