{{- if .Values.podLogs.enabled }}
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: {{ include "burpsuite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "burpsuite.labels" . | nindent 4 }}
spec:
  pipelineStages:
  - cri: {}
  - multiline:
      firstLine: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2} '
      maxWaitTime: 2s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "burpsuite.selectorLabels" . | nindent 6 }}
{{- end }}