{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "burpsuite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "burpsuite.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "burpsuite.fullname" . }}
  namespaceSelector:
    matchNames:
    -  {{ .Release.Namespace }}
  podMetricsEndpoints:
  - interval: 15s
    path: /metrics
    port: "8078"
    relabelings:
    - targetLabel: component
      replacement: enterprise
    - targetLabel: app
      replacement: burpsuite
  - interval: 15s
    path: /metrics
    port: "8088"
    relabelings:
    - targetLabel: component
      replacement: web
    - targetLabel: app
      replacement: burpsuite
  podTargetLabels:
  - app.kubernetes.io/version
  selector:
    matchLabels:
      {{- include "burpsuite.selectorLabels" . | nindent 6 }}
{{- end }}