
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "burpsuite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
{{ include "burpsuite.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "burpsuite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
{{ include "burpsuite.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "burpsuite.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "burpsuite.fullname" . }}
  apiGroup: rbac.authorization.k8s.io