apiVersion: v1
kind: Service
metadata:
  name: {{include "burpsuite.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels: {{- include "burpsuite.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: web-http
      protocol: TCP
      name: http
    - port: {{.Values.service.scimPort}}
      targetPort: web-scim
      protocol: TCP
      name: scim-http
    - port: {{.Values.service.websocketPort}}
      targetPort: ent-api
      protocol: TCP
      name: ws-http
  selector: {{- include "burpsuite.selectorLabels" . | nindent 4}}
