apiVersion: v1
kind: Service
metadata:
  name: {{include "burpsuite.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels: {{- include "burpsuite.labels" . | nindent 4}}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: web-http
      protocol: TCP
      name: http-web
    - port: {{.Values.service.scimPort}}
      targetPort: web-scim
      protocol: TCP
      name: http-scim
    - port: {{.Values.service.websocketPort}}
      targetPort: agent-ws
      protocol: TCP
      name: http-agent-ws
  selector: {{- include "burpsuite.selectorLabels" . | nindent 4}}
