# Default values for scan-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Can only be 1 or 0
replicaCount: 1

global:
  image:
    registry: public.ecr.aws

configuration:
  apiKey: "not-an-api-key"
  enterpriseUrl: "https://not-a-server.url"
  maxConcurrency: 20

controller:
  image:
    registry: ""
    repository: portswigger/scan-controller
    pullPolicy: Always
    tag: ""
    sha256: ""
  nodeSelector:
    kubernetes.io/arch: amd64
  tolerations: []
  affinity: {}

  podLogs: false
  podMonitor: false

scanner:
  image:
    registry: ""
    repository: portswigger/portswigger-hosted-scan
    tag: ""
    sha256: ""
  nodeSelector:
    kubernetes.io/arch: amd64
  tolerations: []
  affinity: {}
  dnsPolicy: ""
  dnsConfig: {}
  # nameservers:
  #   - 192.0.2.1 # this is an example
  # searches:
  #   - ns1.svc.cluster-domain.example
  #   - my.dns.search.suffix
  # options:
  #   - name: ndots
  #     value: "2"
  #   - name: edns0

  podLogs: false
  podMonitor: false

  resources:
    requests:
      cpu: 2
      memory: 14Gi

  jobTemplate: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: scan
      labels:
        {{- include "scan-controller.labels" . | nindent 8 }}
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          labels:
            {{- include "scan-controller.scanner.selectorLabels" . | nindent 8 }}
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
            karpenter.sh/do-not-evict: "true"
            karpenter.sh/do-not-disrupt: "true"
        spec:
          serviceAccount: scanner
          serviceAccountName: scanner
          automountServiceAccountToken: false
          containers:
            - name: scan-container
              env:
                - name: JAVA_OPTS
                  value: -Xms128m -Xmx512m
                - name: BSEE_BURP_JAVA_OPTS
                  value: >-
                    -Xms1g
                    -XX:MaxRAMPercentage=50
              envFrom:
                - secretRef:
                    name: {{ include "scan-controller.fullname" . }}-scanner-env
              image: {{ include "scan-controller.scanner.image" . }}
              imagePullPolicy: Always
              ports:
                - name: management
                  containerPort: 8098
                  protocol: TCP
              {{- with .Values.scanner.resources }}
              resources:
                {{- toYaml . | nindent 12 }}
              {{- end }}
              securityContext:
                runAsUser: 100000
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                privileged: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - mountPath: /home/burpsuite/
                  name: home-burpsuite
                - mountPath: /tmp
                  name: tmp
          volumes:
            - name: home-burpsuite
              emptyDir:
                sizeLimit: 20Gi
            - name: tmp
              emptyDir:
                sizeLimit: 1Gi
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          {{- with .Values.scanner.dnsPolicy }}
          dnsPolicy: {{ . }}
          {{- end }}
          {{- with .Values.scanner.dnsConfig }}
          dnsConfig:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.scanner.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.scanner.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.scanner.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}

extraDeploy: []
