stackId: my-stack-id
aws:
  region: eu-west-1
  account_id: "123456789012"
  oidc_idp_id: "ABCDEF1234567890"
  resourcePrefix: my-prefix-
  iam:
    rolePath: /my-role-path/
    policyPath: /my-policy-path/
    permissionsBoundary: arn:aws:iam::123456789012:policy/my-policy-path/my-policy-name
  s3:
    backupBucketName: my-backup-bucket
cluster:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3@sha256:10fa87e8fbf7f1d7d6be3124ef364068e5844e825b17649bc0b2efbab4b54f69
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  annotations: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 1000m
    limits:
      memory: 1Gi
      cpu: 2000m
  database:
    name: app
    owner: app
    postInitApplicationSQL: []
  storage:
    storageClass: gp3
    size: 1Gi
  walStorage:
    storageClass: gp3
    size: 1Gi
  affinity: {} # https://cloudnative-pg.io/documentation/current/api_reference/#AffinityConfiguration
  nodeMaintenanceWindow:
    inProgress: true
    reusePVC: true
scheduledBackup:
  immediate: True
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  target: prefer-standby
stegostore:
  enabled: true
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  imageName: portswigger-cloud/stegostore
  imageDigest: sha256:c3ee6874873ad41081e95eae17322c6b9424503098262ca0641cf1aa21bf7c08
stegosweep:
  enabled: true
  schedule: "30 1 * * *"
  concurrencyPolicy: Forbid
  daysRetentionDaily: 30
  daysRetentionHourly: 7
  dryRun: false
