apiVersion: v1
kind: Service
metadata:
  name: {{ include "burpsuite.fullname" . }}
  namespace: {{ include "burpsuite.namespace" . }}
  labels:
    {{- include "burpsuite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "burpsuite.selectorLabels" . | nindent 4 }}