apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: stegosweep
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stegosweep
spec:
  pipelineStages:
  - cri: {}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: stegosweep