apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ .Values.aws.iam.rolePrefix }}-{{ .Values.stackId }}
  namespace: {{ .Values.stackId }}
spec:
  deletionPolicy: Delete
  forProvider:
    policyArnRef:
      name: {{ .Values.aws.iam.policyPrefix }}-{{ .Values.stackId }}
    roleRef:
      name: {{ .Values.aws.iam.rolePrefix }}-{{ .Values.stackId }}
  providerConfigRef:
    name: aws