apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres
spec:
  pipelineStages:
  - docker: {}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      cnpg.io/cluster: postgres