apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.aws.resourcePrefix }}{{ .Values.stackId }}
  namespace: {{ .Values.stackId }}
spec:
  immediate: {{ .Values.scheduledBackup.immediate }}
  schedule: "0 {{ randNumeric 1 }}{{ randNumeric 1 }} * * *"
  backupOwnerReference: {{ .Values.scheduledBackup.backupOwnerReference }}
  cluster:
    name: {{ .Values.aws.resourcePrefix }}{{ .Values.stackId }}
  target: prefer-standby
