apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.aws.iam.rolePrefix }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }} 
spec:
  deletionPolicy: Delete
  forProvider:
    path: /{{ .Values.aws.iam.rolePath }}/
    permissionsBoundary: {{ .Values.aws.iam.permissionsBoundary }}
    description: {{ .Release.Name }} database backup iam role
    assumeRolePolicy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Federated": "arn:aws:iam::{{ .Values.aws.accountId }}:oidc-provider/oidc.eks.{{ .Values.aws.region }}.amazonaws.com/id/{{ .Values.aws.oidc_idp_id }}"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                      "StringEquals": {
                          "oidc.eks.{{ .Values.aws.region }}.amazonaws.com/id/{{ .Values.aws.oidc_idp_id }}:aud": "sts.amazonaws.com",
                          "oidc.eks.{{ .Values.aws.region }}.amazonaws.com/id/{{ .Values.aws.oidc_idp_id }}:sub": "system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Name }}"
                      }
                  }
              }
          ]
      }
  providerConfigRef:
    name: aws