{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-init-script
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: database
{{ include "burpsuite.labels" . | indent 4 }}
stringData:
  init-burp-enterprise-db.sh: |
    #!/bin/bash -e

    psql -v ON_ERROR_STOP=1 --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER '${BSEE_ADMIN_REPOSITORY_USERNAME//'/\\'}' PASSWORD '${BSEE_ADMIN_REPOSITORY_PASSWORD//'/\\'}';
      CREATE USER '${BSEE_AGENT_REPOSITORY_USERNAME//'/\\'}' PASSWORD '${BSEE_AGENT_REPOSITORY_PASSWORD//'/\\'}';

      GRANT ALL ON DATABASE {{ quote .Values.postgresql.auth.database }} TO ${BSEE_ADMIN_REPOSITORY_USERNAME//'/\\'};
    EOSQL
{{- end -}}