{{- if .Values.database.useEmbedded -}}
apiVersion: v1
kind: Secret
metadata:
  name: database-vol
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: database
{{ include "burpsuite.labels" . | indent 4 }}
data:
  init.sql: {{ include "burpsuite.database.init" . | b64enc }}
{{- end -}}