apiVersion: v2
name: crossplane-aws-s3-bucket
description: Create an AWS S3 bucket encrypted with an AWS KMS CMK using the crossplane AWS provider
type: application
version: "0.0.6"
kubeVersion: ">=1.24.0-0"
keywords:
  - object storage
  - s3
  - aws
  - crossplane
home: https://portswigger.net/
sources:
  - https://github.com/portswigger-cloud/helm-charts/
maintainers:
  - name: Portswigger Cloud
    email: github-portswigger-cloud@portswigger.net
appVersion: "0.0.1"
