{{- $toolbox := .Values.burpAtToolbox | default dict }}
{{- if $toolbox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scan-controller.fullname" . }}-burp-at-toolbox-env
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- with $toolbox.auth0ClientId }}
  BSEE_AUTH0_CLIENT_ID: {{ . | b64enc }}
{{- end }}
{{- with $toolbox.auth0ClientSecret }}
  BSEE_AUTH0_CLIENT_SECRET: {{ . | b64enc }}
{{- end }}
{{- end }}
