{{- if .Values.scanner.jmxMetrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: burpscanner-jmx-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scan-controller.labels" . | nindent 4 }}
data:
  burpscanner-prometheus.yaml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:{{ .Values.scanner.jmxMetrics.jmxPort }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames: ["java.lang:*"]
    rules:
    - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
      name: java_lang_$1_$4_$3_$2
    - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
      name: java_lang_$1_$3_$2

{{- end }}