apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scan-controller.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  BSEE_SERVER_URL: {{ .Values.configuration.enterpriseUrl | b64enc }}
  BSEE_HOSTED_SCANNING_MACHINE_API_KEY: {{ .Values.configuration.apiKey | b64enc }}
  BSEE_HOSTED_SCAN_JOB_TEMPLATE: {{ include "scan-controller.tplvalues.render" ( dict "value" .Values.scanner.jobTemplate "context" $) | b64enc | b64enc }}
  BSEE_MAX_SCAN_CONCURRENCY: {{ toString .Values.configuration.maxConcurrency | b64enc }}