apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{include "scan-controller.fullname" .}}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "scan-controller.fullname" .}}
subjects:
  - kind: ServiceAccount
    name: {{include "scan-controller.fullname" .}}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{include "scan-controller.fullname" .}}
  apiGroup: rbac.authorization.k8s.io
