apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scan-controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs:
      [
        "get",
        "list",
        "watch",
        "create",
        "update",
        "patch",
        "delete",
        "deletecollection",
      ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scan-controller
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: scan-controller
    apiGroup: ""
roleRef:
  kind: Role
  name: scan-controller
  apiGroup: rbac.authorization.k8s.io
