apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scan-controller.fullname" . }}-scanner-env
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  BSEE_WEB_SERVER_URL: {{ .Values.configuration.enterpriseUrl | b64enc }}
  BSEE_HOSTED_SCANNING_MACHINE_API_KEY: {{ .Values.configuration.apiKey | b64enc }}