apiVersion: v1
kind: ServiceAccount
metadata:
  name: scan-controller
  namespace: {{ .Release.Namespace }}
  labels: {{- include "scan-controller.labels" . | nindent 4}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner
  namespace: {{ .Release.Namespace }}
  labels: {{- include "scan-controller.labels" . | nindent 4}}
automountServiceAccountToken: false
