apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scan-controller.fullname" . }}
  labels:
    {{- include "scan-controller.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scan-controller.fullname" . }}-scanner
  labels:
    {{- include "scan-controller.labels" . | nindent 4 }}
automountServiceAccountToken: false
