apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: stegostore
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stegostore
spec:
  pipelineStages:
  - docker: {}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: stegostore