apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: stegostore
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stegostore
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ .Release.Namespace }}
  selector:
    matchLabels: stegostore
  relabelings:
    - action: replace
      sourceLabels:
        - __meta_kubernetes_pod_container_name
      targetLabel: container
    - action: replace
      sourceLabels:
        - __meta_kubernetes_pod_name
      targetLabel: pod
    - action: replace
      sourceLabels:
        - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      sourceLabels:
        - __meta_kubernetes_pod_container_id
      targetLabel: tmp_container_id
    - action: replace
      sourceLabels:
        - __meta_kubernetes_pod_uid
      targetLabel: pod_uid
    - action: replace
      sourceLabels:
        - __meta_kubernetes_pod_uid
      targetLabel: pod_uid