apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.aws.resourcePrefix }}{{ .Values.stackId }}
  namespace: {{ .Release.Namespace }}
spec:
  deletionPolicy: Delete
  forProvider:
    region: {{ .Values.aws.region }}
    forceDestroy: True
    tags:
      stack-id: {{ .Values.stackId }}
    {{- with .Values.aws.s3.tags }}
      {{- toYaml . | nindent 6 }}
    {{- end}}
  providerConfigRef:
    name: aws