apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketServerSideEncryptionConfiguration
metadata:
  name: {{ .Values.aws.resourcePrefix }}{{ .Values.stackId }}
  namespace: {{ .Values.stackId }}
spec:
  deletionPolicy: Delete
  forProvider:
    region: {{ .Values.aws.region }}
    bucket: {{ .Values.aws.resourcePrefix }}{{ .Values.stackId }}
    rule:
      - applyServerSideEncryptionByDefault:
        - kmsMasterKeyIdRef:
            name: {{ .Values.aws.resourcePrefix }}{{ .Values.stackId }}
          sseAlgorithm: aws:kms
        bucketKeyEnabled: True
  providerConfigRef:
    name: aws